# Generated by Django 4.2.7 on 2024-06-14 11:39

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Avatar',
                'verbose_name_plural': 'User Avatars',
            },
        ),
        migrations.CreateModel(
            name='RefarbishedDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('previous_total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 14, 11, 39, 46, 833450, tzinfo=datetime.timezone.utc))),
                ('date_modified', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 14, 11, 39, 46, 833462, tzinfo=datetime.timezone.utc))),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refarbished Device',
                'verbose_name_plural': 'Refarbished Devices',
                'db_table': 'refarbished_devices',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_notification', models.TextField()),
                ('personal_notification', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appliances',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Appliance_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_sold', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appliance Sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Accessory_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 14, 11, 39, 46, 832626, tzinfo=datetime.timezone.utc))),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory Sales',
                'verbose_name_plural': 'Accessory Sales',
                'db_table': 'accessory_sales',
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('previous_total', models.IntegerField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 14, 11, 39, 46, 832209, tzinfo=datetime.timezone.utc))),
                ('date_modified', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 14, 11, 39, 46, 832223, tzinfo=datetime.timezone.utc))),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'db_table': 'accessories',
            },
        ),
        migrations.CreateModel(
            name='MainStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_imei', models.CharField(max_length=15, unique=True)),
                ('device_imei_2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(default='Tecno', max_length=25, null=True)),
                ('spec', models.CharField(blank=True, max_length=25, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('assigned', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('on_display', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('faulty', models.BooleanField(default=False)),
                ('issue', models.BooleanField(default=False)),
                ('sales_type', models.CharField(choices=[('##', '##'), ('Cash', 'Cash'), ('Loan', 'Loan')], default='##', max_length=10, null=True)),
                ('contract_no', models.CharField(default='##', max_length=9, null=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('stock_out_date', models.DateField(default=django.utils.timezone.now)),
                ('collected_on', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assigned_from', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('trans_image', models.ImageField(blank=True, null=True, upload_to='Cash_Transactions')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Phones Storage',
                'verbose_name_plural': 'SmartPhones storage',
                'indexes': [models.Index(fields=['device_imei', 'phone_type', 'in_stock', 'assigned'], name='gadgetsCorn_device__25128c_idx')],
            },
        ),
    ]
