# Generated by Django 4.2.7 on 2024-06-04 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessary_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 4, 11, 20, 29, 538869, tzinfo=datetime.timezone.utc))),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory Sales',
                'verbose_name_plural': 'Accessory Sales',
                'db_table': 'accessary_sales',
            },
        ),
        migrations.AlterModelOptions(
            name='mainstorage',
            options={'verbose_name': 'New Phones Storage', 'verbose_name_plural': 'New Phones storage'},
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='cost',
            new_name='cost_per_item',
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='device_name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='mainstorage',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='mainstorage',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='mainstorage',
            name='os',
        ),
        migrations.RemoveField(
            model_name='mainstorage',
            name='screen_size',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 4, 11, 20, 29, 537971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 4, 11, 20, 29, 538007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 4, 11, 20, 29, 540069, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 4, 11, 20, 29, 540094, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Airtel_mifi_storage',
        ),
    ]
