# Generated by Django 4.2.7 on 2025-03-28 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0002_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 28, 23, 21, 26, 635509, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 28, 23, 21, 26, 635524, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 28, 23, 21, 26, 635915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 28, 23, 21, 26, 636494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 3, 28, 23, 21, 26, 636505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField(default=3)),
                ('year', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Sales Target',
                'verbose_name_plural': 'Sales Targets',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
