# Generated by Django 4.2.7 on 2024-06-10 00:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0002_accessary_sales_alter_mainstorage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 10, 0, 18, 36, 896992, tzinfo=datetime.timezone.utc))),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessory Sales',
                'verbose_name_plural': 'Accessory Sales',
                'db_table': 'accessory_sales',
            },
        ),
        migrations.AlterModelOptions(
            name='mainstorage',
            options={'verbose_name': 'New Phones Storage', 'verbose_name_plural': 'SmartPhones storage'},
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 10, 0, 18, 36, 896405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 10, 0, 18, 36, 896427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 10, 0, 18, 36, 897585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 10, 0, 18, 36, 897596, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Accessary_Sales',
        ),
    ]
