# Generated by Django 4.2.7 on 2025-04-05 08:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0004_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refarbisheddevices',
            old_name='device_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='refarbisheddevices',
            name='original_price',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 365412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 365426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 365803, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dailyexpenses',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 366470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 366481, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='month',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='RefarbishedDevicesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_sold', models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 8, 34, 30, 366866, tzinfo=datetime.timezone.utc))),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refarbished Sale',
                'verbose_name_plural': 'Refarbished Sales',
                'db_table': 'refarbished_devices_sales',
            },
        ),
    ]
