# Generated by Django 4.2.7 on 2024-06-11 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0004_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance_sales',
            name='price_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appliance_sales',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 11, 0, 7, 5, 458633, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 11, 0, 7, 5, 458649, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 11, 0, 7, 5, 459102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 11, 0, 7, 5, 459674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 11, 0, 7, 5, 459685, tzinfo=datetime.timezone.utc)),
        ),
    ]
