# Generated by Django 4.2.7 on 2025-04-05 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0005_rename_device_name_refarbisheddevices_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 471319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 471332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 471731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 472414, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 472426, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevicessales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 9, 47, 51, 472812, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('current', 'Current Liability'), ('non_current', 'Non-Current Liability')], max_length=255)),
                ('creditor', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
                'db_table': 'liabilities',
                'indexes': [models.Index(fields=['effective_date'], name='liabilities_effecti_524655_idx')],
            },
        ),
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_purchased', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('useful_life', models.IntegerField()),
                ('salvage_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'db_table': 'fixed_assets',
                'indexes': [models.Index(fields=['date_purchased'], name='fixed_asset_date_pu_470622_idx')],
            },
        ),
    ]
