# Generated by Django 4.2.7 on 2025-04-05 10:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0006_alter_accessories_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenses',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyexpenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 197305, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 197319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 197706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dailyexpenses',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 198396, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 198408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevicessales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 5, 10, 32, 41, 198788, tzinfo=datetime.timezone.utc)),
        ),
    ]
