# Generated by Django 4.2.7 on 2025-04-07 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgetsCorner', '0007_dailyexpenses_category_dailyexpenses_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexpenses',
            name='name',
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 103420, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 103434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accessory_sales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 103819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_added',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 104506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevices',
            name='date_modified',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 104518, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refarbisheddevicessales',
            name='date_sold',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 4, 7, 12, 34, 37, 104905, tzinfo=datetime.timezone.utc)),
        ),
    ]
